package com.google.android.gms.common.api.internal;

import com.google.android.gms.common.internal.*;
import java.util.concurrent.*;
import com.google.android.gms.common.api.*;
import android.support.annotation.*;

public class zzt<R extends Result> extends PendingResult<R>
{
    private final Status zzUX;
    
    public zzt(final Status zzUX) {
        zzx.zzb(zzUX, "Status must not be null");
        zzx.zzb(!zzUX.isSuccess(), (Object)"Status must not be success");
        this.zzUX = zzUX;
    }
    
    @NonNull
    @Override
    public R await() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }
    
    @NonNull
    @Override
    public R await(final long n, @NonNull final TimeUnit timeUnit) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }
    
    @Override
    public void cancel() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }
    
    @NonNull
    Status getStatus() {
        return this.zzUX;
    }
    
    @Override
    public boolean isCanceled() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }
    
    @Override
    public void setResultCallback(@NonNull final ResultCallback<? super R> resultCallback) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }
    
    @Override
    public void setResultCallback(@NonNull final ResultCallback<? super R> resultCallback, final long n, @NonNull final TimeUnit timeUnit) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }
    
    @NonNull
    @Override
    public <S extends Result> TransformedResult<S> then(@NonNull final ResultTransform<? super R, ? extends S> resultTransform) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }
    
    @Override
    public void zza(@NonNull final zza zza) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }
    
    @Nullable
    @Override
    public Integer zzpa() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }
}
